version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      root-pub-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pub"
    directory: "/bdk_demo"
    schedule:
      interval: "weekly"
    groups:
      demo-pub-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/native"
    schedule:
      interval: "weekly"
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
